export const DirectoryTypes = {
  LOAD_DATA: "LOAD_DATA",
  FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",
  FILTER_BY_PRICE: "FILTER_BY_PRICE",
  LOAD_NEW_PAGE: "LOAD_NEW_PAGE",
  LOAD_EXACT_PAGE: "LOAD_EXACT_PAGE",
};
